# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: local
  hosts: all
  pre_tasks:
    - import_tasks: sync.yml
  roles:
    - name: ansible
      tags: ansible
    - name: bash
      tags: bash
    - name: dotfiles
      tags: dotfiles
    - name: environment
      tags: environment
    - name: emacs
      tags: emacs
    - name: git
      tags: git
    - name: gnome
      tags: gnome
    - name: gpg
      tags: gpg
