# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: CC-BY-SA-4.0
#+TITLE: lndmrk's dotfiles
#+AUTHOR: Emil Lundmark

These are my personal dotfiles---in fact, this is how my entire environment is
set up and configured. A machine is provisioned by running an
[[https://www.ansible.com/][Ansible]] playbook. Components are organized into
Ansible /roles/. For convenience, all roles are included in a single playbook,
with each role defining a variable =${ROLE}_role= that determines if the role's
tasks should be imported.

Unfortunately I can not share everything, so there is also support for importing
a private playbook that lives in a private repository.

* Install

Install everything by running

#+BEGIN_EXAMPLE
$ ansible-pull --url="${REPO}" --directory="${DEST}" --ask-become-pass
#+END_EXAMPLE

or alternatively

#+BEGIN_EXAMPLE
$ git clone "${REPO}"
$ cd "$(basename "${REPO}" .git)"
$ bin/dotfiles deploy
#+END_EXAMPLE

Since =dotfiles deploy= uses Ansible under the hood, additional command line
arguments that Ansible understands can be appended.

* Test

A set of compliance tests can be run with

#+BEGIN_EXAMPLE
$ dotfiles test
#+END_EXAMPLE

This can be configured to run before every commit.

#+BEGIN_EXAMPLE
$ cat <<EOF >.git/hooks/pre-commit
#!/bin/sh
exec dotfiles test
EOF
$ chmod a+x .git/hooks/pre-commit
#+END_EXAMPLE

* Boilerplate

** Private Repository

A new private repository can be created like so:

#+BEGIN_EXAMPLE
$ git init private/
$ cd private/
$ mkdir inventory/ roles/
$ touch inventory/hosts.yml
$ cat <<EOF >private.yml
---
- name: private
  hosts: all
EOF
$ ln --symbolic ../.gitignore
#+END_EXAMPLE

* License

This project is [[https://reuse.software/][REUSE]] compliant. The copyright and
license information for all files are specified using SPDX tags.
