# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: CC-BY-SA-4.0
#+TITLE: lndmrk's dotfiles
#+AUTHOR: Emil Lundmark

These are my personal dotfiles organized as an
[[https://www.ansible.com/][Ansible]] collection.

* Usage

This describes how I use this collection with my private playbooks. Since I
don't intent to upload the collection to any Ansible Galaxy server I instead use
project-local collections by configuring =ansible.cfg= like this:

#+BEGIN_EXAMPLE
[defaults]
collections_path = ./
#+END_EXAMPLE

I then clone this repository into =ansible_collections/lndmrk/dotfiles/=. It's
then possible to use the roles from this collection in playbooks, for example:

#+BEGIN_EXAMPLE
---
- hosts: localhost
  roles:
    - lndmrk.dotfiles.environment
#+END_EXAMPLE

* Test

A set of compliance tests can be run with

#+BEGIN_EXAMPLE
$ bin/test
#+END_EXAMPLE

This should be configured to run before every commit.

#+BEGIN_EXAMPLE
$ ln -s ../../bin/test .git/hooks/pre-commit
#+END_EXAMPLE

* License

This project is [[https://reuse.software/][REUSE]] compliant. The copyright and
license information for all files are specified using SPDX tags.
