# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: CC-BY-SA-4.0
#+TITLE: lndmrk's dotfiles
#+AUTHOR: Emil Lundmark

These are my personal dotfiles organized as an
[[https://www.ansible.com/][Ansible]] collection.

* Usage

This describes how I use this collection with my private playbooks. Since I
don't intent to upload the collection to any Ansible Galaxy server I instead use
project-local collections by configuring =ansible.cfg= like this:

#+begin_example
[defaults]
collections_path = ./
#+end_example

I then clone this repository into =ansible_collections/lndmrk/dotfiles/=. It's
then possible to use the roles from this collection in playbooks, for example:

#+begin_example
---
- hosts: localhost
  roles:
    - lndmrk.dotfiles.environment
#+end_example

* Test

A set of compliance tests can be run with

#+begin_example
$ bin/test
#+end_example

This should be configured to run before every commit.

#+begin_example
$ ln -s ../../bin/test .git/hooks/pre-commit
#+end_example

* License

This project is [[https://reuse.software/][REUSE]] compliant. The copyright and
license information for all files are specified using SPDX tags.
