#!/bin/bash

set -euo pipefail

cd "$(dirname "$(realpath "$0")")"

get_distro() {
  (if [[ -f /etc/lsb-release ]]; then
     # shellcheck disable=SC1091
     (. /etc/lsb-release && echo "${DISTRIB_ID}")
   elif [[ -f /etc/os-release ]]; then
     # shellcheck disable=SC1091
     (. /etc/os-release && echo "${ID}")
   else
     uname --kernel-name
   fi) | tr '[:upper:]' '[:lower:]'
}

for file in "setup-$(get_distro).sh" "local/setup-local.sh"; do
  if [[ -f "${file}" ]]; then
    # shellcheck source=/dev/null
    . "${file}"
  fi
done

# xdg
for dir in Public Templates; do
  hidden_dir="${HOME}/.${dir,,}"
  if [[ -d "${HOME}/${dir}" ]]; then
    mv "${HOME}/${dir}" "${hidden_dir}"
  else
    mkdir --parents "${hidden_dir}"
  fi
done

echo -e "\e[1m\e[32mSetup completed successfully\e[39m\e[0m"
