#!/bin/bash

cd "$(dirname "$(realpath "$0")")" || exit 1

git --version > /dev/null

gpg2 --version > /dev/null

if [[ -f local/test-local.sh ]]; then
  # shellcheck source=/dev/null
  . local/test-local.sh
fi

echo -e "\\e[1;32mAll tests completed\\e[0m"
