#!/bin/bash

set -euo pipefail

cd "$(dirname "$(realpath "$0")")/sandbox/"

for distro in debian fedora; do
  echo -e "Sandbox test for \\e[1;34m${distro}\\e[0m"
  (cd "${distro}" || exit 1
   vagrant up
   vagrant provision
   vagrant ssh --command=/vagrant/test
   vagrant halt)
done

echo -e "\\e[1;32mSandbox test succeeded\\e[0m"
