#!/bin/bash

cd "$(dirname "$(realpath "$0")")" || exit 1

if ! emacs --version | grep --quiet "^GNU Emacs 26" ; then
  echo -n -e "\\e[33m"
  emacs --version
  echo -n -e "\\e[0m"
fi

dircolors --version > /dev/null

gio --version > /dev/null

git --version > /dev/null

gpg2 --version > /dev/null

pandoc --version > /dev/null

if [[ -f local/test-local.sh ]]; then
  # shellcheck source=/dev/null
  . local/test-local.sh
fi

echo -e "\\e[1;32mAll tests completed\\e[0m"
