#!/bin/bash

cd "$(dirname "$(realpath "$0")")" || exit 1

shellcheck --version > /dev/null

shellcheck test
shellcheck test-sandbox

shellcheck --shell=bash setup setup-*.sh

while read -r file; do
  if [[ "$(file --brief "${file}")" == "Bourne-Again shell script"* ]]; then
    shellcheck "${file}"
  fi
done < <(find common/bin/.local/bin/* -type f)

bash --version > /dev/null
shellcheck --shell=bash \
  common/environment/.profile \
  common/bash/.bash*

if ! emacs --version | grep --quiet "^GNU Emacs 25"; then
  echo -n -e "\\e[33m"
  emacs --version
  echo -n -e "\\e[0m"
fi

dircolors --version > /dev/null

gio --version > /dev/null

git --version > /dev/null

pandoc --version > /dev/null

stow --version > /dev/null

if [[ -f local/test-local.sh ]]; then
  # shellcheck source=/dev/null
  . local/test-local.sh
fi

echo -e "\\e[1;32mAll tests completed\\e[0m"
