# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later

FROM {{ item.image }}

RUN dnf --refresh --assumeyes install \
    python3 \
    python3-dnf \
    && dnf clean all

RUN useradd user && \
    echo "user ALL = (ALL) NOPASSWD: ALL" >/etc/sudoers.d/user
USER user
