# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install dependencies
  package:
    name: ansible
  become: true

- name: Install Fedora dependencies
  package:
    name: python3-cookiecutter
  become: true
  when: ansible_distribution_file_variety == 'RedHat'

- name: Install Debian dependencies
  package:
    name: cookiecutter
  become: true
  when: ansible_distribution_file_variety == 'Debian'

- name: Install test dependencies
  package:
    name:
      - podman
      - python3-devel
      - python3-libselinux
      - python3-testinfra
  become: true
  when: ansible_distribution_file_variety == 'RedHat'

- name: Create local bin directory
  file:
    path: ~/.local/bin/
    state: directory

- name: Install bin
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.local/bin/{{ item }}"
    state: link
  loop:
    - dotfiles
