$provision_base = <<EOF
echo "vagrant:vagrant" | chpasswd
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install --yes task-desktop task-gnome-desktop
systemctl set-default graphical.target
systemctl start gdm.service
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision "shell", inline: $provision_base
  config.vm.provision "shell",
                      path: "../provision-dotfiles.sh",
                      privileged: false
  config.vm.synced_folder "../../", "/vagrant", type: "sshfs"
  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 2048
    lv.graphics_type = "spice"
    lv.video_type = "virtio"
  end
end
