# SPDX-FileCopyrightText: 2020 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install
  package:
    name:
      - python3
      - python3-virtualenv
  become: true
