# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Create XDG user dirs
  shell: |
    changed=""
    for dir in \
        DESKTOP DOWNLOAD TEMPLATES PUBLICSHARE DOCUMENTS MUSIC PICTURES VIDEOS
    do
        dir=$(xdg-user-dir "${dir}")
        if [ ! -d "${dir}" ]; then
            mkdir "${dir}"
            changed=true
        fi
    done
    [ -n "${changed}" ] && exit 3
    exit 0
  register: cmd
  changed_when: cmd.rc == 3
  failed_when: cmd.rc not in (0, 3)
