# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install
  package:
    name: git
  become: true

- name: Create local config directory
  file:
    path: ~/.config/git/
    state: directory
    mode: 0775

- name: Install config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/git/{{ item }}"
    state: link
  loop:
    - config
    - ignore
