#!/bin/bash
#
# SPDX-FileCopyrightText: 2020 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later

# Assume Acer XV273K
# https://github.com/ddccontrol/ddccontrol-db/blob/aecf351eff29da88b488b18e9bb632020bad54e8/db/monitor/ACR06B1.xml#L36
readonly ADDRESS=0x60
readonly DP1=15
readonly DP2=16

change_input() (
  local address="${1}"
  local value="${2}"
  shopt -s nullglob
  for dev in /dev/ddc-monitor-*; do
    ddccontrol -r "${address}" "dev:${dev}" -w "${value}" "${dev}"
  done
)

main() {
  local input="${1,,}"
  input="${input//-}"
  if [[ "${input}" = dp1 ]]; then
    change_input "${ADDRESS}" "${DP1}"
  elif [[ "${input}" = dp2 ]]; then
    change_input "${ADDRESS}" "${DP2}"
  else
    echo >&2 "Invalid input: ${1}"
    exit 1
  fi
}

main "${@}"
