# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install
  package:
    name: emacs
  become: true

- name: Install companion tools
  package:
    name:
      - clang
      - clang-format
      - clang-tidy
      - clang-tools
      - pandoc
      - python3
      - python3-proselint
      - python3-virtualenv
      - shellcheck
      - yamllint
  become: true
  when: ansible_distribution_file_variety == 'Debian'

- name: Install companion tools
  package:
    name:
      - ShellCheck
      - clang
      - pandoc
      - proselint
      - python3
      - python3-virtualenv
      - yamllint
  become: true
  when: ansible_distribution_file_variety == 'RedHat'

- name: Create Emacs config directory
  file:
    path: ~/.config/emacs/
    state: directory

- name: Create symlink to old Emacs config directory
  file:
    src: ~/.config/emacs
    dest: ~/.emacs.d
    state: link

- name: Install config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/emacs/{{ item }}"
    state: link
    force: true
  loop:
    - config.org
    - early-init.el
    - init.el

- name: Create systemd user config directory
  file:
    path: ~/.config/systemd/user/
    state: directory

- name: Install emacs.socket
  file:
    src: "{{ role_path }}/files/systemd/{{ item }}"
    dest: "~/.config/systemd/user/{{ item }}"
    state: link
  loop:
    - emacs.socket

- name: Enable emacs.socket
  systemd:
    name: emacs.socket
    daemon_reload: true
    scope: user
    enabled: true
    state: started

- name: Create profile.d directory
  file:
    path: ~/.config/profile.d/
    state: directory

- name: Install profile.d config file
  file:
    src: "{{ role_path }}/files/profile.d/{{ item }}"
    dest: "~/.config/profile.d/{{ item }}"
    state: link
  loop:
    - 20-emacs.sh

- name: Create application entries directory
  file:
    path: ~/.local/share/applications/
    state: directory

- name: Override Emacs desktop entry to use emacsclient
  file:
    src: "{{ role_path }}/files/applications/{{ item }}"
    dest: "~/.local/share/applications/{{ item }}"
    state: link
  loop:
    - emacs.desktop
