# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install
  package:
    name: emacs
  become: true

- name: Install companion tools
  package:
    name:
      - pandoc
      - >-
        {{ 'ShellCheck' if ansible_distribution_file_variety == 'RedHat' else
           'shellcheck' }}
      - >-
        {{ 'proselint' if ansible_distribution_file_variety == 'RedHat' else
           'python3-proselint' }}
      - yamllint
  become: true

- name: Create Emacs config directory
  file:
    path: ~/.config/emacs/
    state: directory
    mode: 0775

- name: Create symlink to old Emacs config directory
  file:
    src: ~/.config/emacs
    dest: ~/.emacs.d
    state: link

- name: Install config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/emacs/{{ item }}"
    state: link
    force: true
  loop:
    - config.org
    - early-init.el
    - init.el

- name: Create profile.d directory
  file:
    path: ~/.config/profile.d/
    state: directory
    mode: 0775

- name: Install profile.d config file
  file:
    src: "{{ role_path }}/files/profile.d/{{ item }}"
    dest: "~/.config/profile.d/{{ item }}"
    state: link
  loop:
    - 20-emacs.sh
