# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later

FROM {{ item.image }}

RUN apt-get update && apt-get --yes install \
    sudo \
    python3 \
    python3-apt \
    && apt-get clean

RUN useradd --create-home user && \
    echo "user ALL = (ALL) NOPASSWD: ALL" >/etc/sudoers.d/user
USER user
