# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install
  package:
    name: gnupg
  become: true
  tags: become

- name: Install smart card support
  package:
    name: scdaemon
  become: true
  when: ansible_distribution_file_variety == 'Debian'
  tags: become

- name: Install smart card support
  package:
    name: pcsc-lite
  become: true
  when: ansible_distribution_file_variety == 'RedHat'
  tags: become

- name: Create config directory
  file:
    path: ~/.gnupg/
    mode: 0700
    state: directory

- name: Install config file
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    state: link
  loop:
    - gpg.conf

- name: Create bashrc.d directory
  file:
    path: ~/.config/bash/bashrc.d/
    state: directory

- name: Install bashrc.d config files
  file:
    src: "{{ item }}"
    dest: "~/.config/bash/bashrc.d/{{ item | basename }}"
    state: link
  with_fileglob:
    - bashrc.d/*

- name: Configure SSH support
  include_tasks: ssh.yml
  when: gpg_ssh_support
