# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install
  package:
    name: gnupg
  become: true

- name: Install smart card support
  package:
    name: scdaemon
  become: true
  when: ansible_distribution_file_variety == 'Debian'

- name: Install smart card support
  package:
    name: pcsc-lite
  become: true
  when: ansible_distribution_file_variety == 'RedHat'

- name: Create config directory
  file:
    path: ~/.gnupg/
    mode: 0700
    state: directory

- name: Install config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    state: link
  loop:
    - gpg-agent.conf
    - gpg.conf
    - sshcontrol

# TODO: These files are only installed inside /usr/share/doc/ on RHEL
# derivatives. Since documentation is not present inside containers, these files
# are instead included with the role.
# https://bugzilla.redhat.com/show_bug.cgi?id=1560348
- name: Install systemd user units
  include_tasks: systemd-user.yml
  when: ansible_distribution_file_variety == 'RedHat'

- name: Enable gpg-agent sockets
  systemd:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop:
    - gpg-agent-ssh.socket
    - gpg-agent.socket
  tags: molecule-notest

- name: Create autostart directory
  file:
    path: ~/.config/autostart/
    state: directory

- name: Disable autostart for Gnome Keyring SSH agent
  copy:
    dest: ~/.config/autostart/gnome-keyring-ssh.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Hidden=true
