# SPDX-FileCopyrightText: 2019 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install sshcontrol
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    state: link
  loop:
    - sshcontrol

- name: Enable SSH support
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    line: enable-ssh-support
    create: true
  when: gpg_ssh_enabled

- name: Create gpg-agent-ssh.socket.d directory
  file:
    path: ~/.config/systemd/user/gpg-agent-ssh.socket.d/
    state: directory
  when: gpg_ssh_enabled

- name: Configure SSH_AUTH_SOCK
  copy:
    dest: ~/.config/systemd/user/gpg-agent-ssh.socket.d/environment.conf
    content: |
      [Socket]
      ExecStartPost=/usr/bin/systemctl --user set-environment \
          SSH_AUTH_SOCK=%t/gnupg/S.gpg-agent.ssh
  when: gpg_ssh_enabled

- name: Enable gpg-agent-ssh socket
  systemd:
    name: gpg-agent-ssh.socket
    enabled: true
    scope: user

- name: Create autostart directory
  file:
    path: ~/.config/autostart/
    state: directory

- name: Disable autostart for Gnome Keyring SSH agent
  copy:
    dest: ~/.config/autostart/gnome-keyring-ssh.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Hidden=true
