# SPDX-FileCopyrightText: 2020 Emil Lundmark <emil@lndmrk.se>
# SPDX-License-Identifier: GPL-3.0-or-later
---
name: Test
# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore:
      - wip-*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reuse
      - name: Run tests
        run: reuse lint
